Refactor output
mario-kr/antikoerper pull request #1
Opened 2018-11-03 13:00 UTC by mario-kr

PR is only for reviewing purposes, @matthiasbeyer, would you do me the favor?

2018-11-03 13:03 UTC, mario-kr commented
This configuration may be used to run it:

```
[general]
shell = "/usr/bin/bash"

[[output]]
type = "file"
base_path = "/tmp"

[[items]]
key = "ak-file-load"
interval = 6
input.type = "file"
input.path = "/proc/loadavg"
digest.type = "regex"
digest.regex = "(?P<load1m>\\d+\\.\\d\\d)\\s(?P<load5m>\\d+\\.\\d\\d)\\s(?P<load15m>\\d+\\.\\d\\d)"
```

2018-11-04 17:00 UTC, matthiasbeyer requested changes
Besides the annotations: 2b508ee can be squashed into 3fb8041

2018-11-04 17:00 UTC, matthiasbeyer commented on src/main.rs
> +    for mut output in config.output.clone() {
No need to clone here, you can `iter_mut()` right?

2018-11-04 17:00 UTC, matthiasbeyer commented on src/output.rs
> +            always_write_raw: file_always_raw_default()
It seems that you use these functions only here, am I right? Why not make them values here and remove the functions? Either way, it might be a good idea to add the `#[inline]' attribute to the functions.

2018-11-04 17:00 UTC, matthiasbeyer commented on src/main.rs
> +    for mut output in config.output.clone() {
Same here: Why not use `iter_mut()` instead of clone?

2018-11-04 17:03 UTC, mario-kr commented on src/main.rs
> +    for mut output in config.output.clone() {
i changed it to iterators in #2, though maybe not quite properly.

2018-11-04 17:03 UTC, mario-kr commented on src/output.rs
> +            always_write_raw: file_always_raw_default()
the functions are always tagged for serde to use if these values are not given

2018-11-04 17:09 UTC, matthiasbeyer commented on src/output.rs
> +            always_write_raw: file_always_raw_default()
Ah, nvm.

2020-02-16 10:31 UTC, closed without merging